require("avatus.plugins-setup")
require("avatus.core.options")
require("avatus.core.keymaps")
require("avatus.core.colorscheme")
require("avatus.plugins.comment")
require("avatus.plugins.neotree")
require("avatus.plugins.autocommands")
-- require("avatus.plugins.lualine")
require("avatus.plugins.telescope")
require("avatus.plugins.nvim-cmp")
require("avatus.plugins.lsp.mason")
require("avatus.plugins.lsp.lspsaga")
require("avatus.plugins.lsp.lspconfig")
require("avatus.plugins.lsp.null-ls")
require("avatus.plugins.autopairs")
require("avatus.plugins.treesitter")
require("avatus.plugins.gitsigns")
